CREATE DATABASE IF NOT EXISTS school_example
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE school_example;

CREATE TABLE IF NOT EXISTS books (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(150) NOT NULL,
    publication_year SMALLINT UNSIGNED NOT NULL
) ENGINE=InnoDB;
