CREATE DATABASE IF NOT EXISTS school_ex03
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE school_ex03;

CREATE TABLE IF NOT EXISTS students (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    age TINYINT UNSIGNED NOT NULL,
    student_code VARCHAR(30) NOT NULL UNIQUE
) ENGINE=InnoDB;
